build-trust/ockam-website

- LICENSE
> add apache 2 license

- .gitignore
- README.md
- cli/HELP.md
- cli/README.md
- cli/example.cli.config
- cli/ockam.aliases
* Add internal CLI for project setup
Resolves: OCM-6
> feat: CLI for project

- gatsby-config.js
Add siteUrl param
Resolves: #24
> fix: gatsby sitemap plugin fails

- src/components/pages/homepage/BuildersSection.js
- src/components/pages/homepage/GetStartedSection.js
- src/components/pages/homepage/HeaderSection.js
- src/components/pages/homepage/SeamlessConnectedSection.js
- src/components/pages/team/HeaderSection.js
- src/components/pages/team/ValuesSection.js
- src/content/learn/blog/values_and_virtues_on_the_Ockam_Team.md
edits on the following pages
- ockam.io/
- /team
- blog/{values and virtues} 
This change will cause a bug in design on the /team page
Issue #35
> fix: content edits

- src/components/pages/product/CloudSdkSection.js
- src/components/pages/product/RegistrySection.js
fix section subheading copy to match the underlying content
> fix: product page subheading text

- README.md
- config.js
- src/content/learn/blog/iot_device_security.md
Updated 
- metadata for SEO and social links
- repository readme introduction
- blog title (remove duplicate)
> chore: content edits

- cli/HELP.md
- cli/ockam.aliases
- terraform/README.md
- terraform/cdn.tf
- terraform/main.tf.example
- terraform/variables.tf
I also added some ockam commands and improvements.
> chore: Enable caching on CDN

- src/components/Menu/MenuItems.js
Changing order to limit the effects of switching between light dark mode
> feat: Switch order of `team` menu link

- config.js
- gatsby-browser.js
- gatsby-config.js
- src/components/EditOnGithubLink.js
- src/components/Link.js
- src/components/Pre.js
- src/components/SocialBox.js
- src/components/blog/LearnPost.js
- src/components/blog/Post.js
- src/components/blog/ShareButton.js
- src/components/learn/LearnSidebar/LearnSidebar.js
- src/components/learn/TableOfContent/TableOfContent.js
- src/components/learn/TableOfContent/TableOfContentItem.js
- src/components/learn/TableOfContent/index.js
- src/components/mdxComponents/index.js
- src/templates/LearnTemplate.js
- src/theme/defaultTheme.js
- src/theme/lightTheme.js
- right sidebar table of content
- move edit page to right sidebar
- generate anchor link for headings
> feat: add table of content and anchor for headings

- gatsby-browser.js
- src/components/Heading.js
- src/components/blog/PostLink.js
- src/components/mdxComponents/index.js
- src/components/pages/DefaultGridSection.js
- src/components/pages/StickySection.js
- src/components/pages/product/CloudSdkSection.js
- src/components/pages/product/RegistrySection.js
- src/components/pages/product/cloud-sdk/ElementsSection.js
- src/components/pages/product/edge-sdk/ElementsSection.js
- src/components/pages/product/embedded-sdk/ElementsSection.js
- src/components/pages/product/router/DescriptionSection.js
- src/components/pages/team/JoinTeam.js
- src/utils/isLearnPath.js
- make Heading component linkable
> feat: add anchors for headings

- src/components/Menu/DropdownLink.js
- src/components/Menu/MenuItems.js
- src/components/NextPrevious.js
- src/components/pages/PageSection.js
- src/components/pages/product/edge-sdk/ElementsSection.js
- src/components/pages/team/JoinTeam.js
- src/components/pages/team/ValuesSection.js
- src/templates/LearnTemplate.js
- overview and open roles dropdown for 'team'
- align next/prev buttons
- right sidebar top offset
> feat: minor improvements before release

- src/components/mdxComponents/Anchor.js
Making all relative links ( `./*` ) generated from md files to be relative to current folder,
not base url of the website.
> feat: relative links in md files

- gatsby-browser.js
- package.json
- src/components/Heading.js
fixes issue with scrolling to anchor in production build, use github-slugger to generate slug for anchors
> fix: jump to anchor and duplicated id slug

- src/content/learn/guides/contributions/Ockam_C_Coding_Standard.md
> content: ockam c coding standard doc file

- config.js
- src/components/learn/TableOfContent/TableOfContent.js
- src/content/learn/guides/contributions/ockam_style_guide.md
- src/hooks/useActiveHashInViewport.js
- src/templates/LearnTemplate.js
- src/utils/isNotEmptyArray.js
- make table of content interactive while scrolling
- add second level of content based on h3
> feat: table of content improvements

- src/content/learn/guides/contributions/CONTRIBUTING.md
- src/content/learn/guides/contributions/cla.md
- src/content/learn/guides/team/conduct
- src/content/learn/guides/team/engineering_levels.md
Add code of conduct and fix links elsewhere to go to this endpoint.
> docs: add code of conduct + links

- src/content/learn/guides/contributions/cla.md
- src/content/learn/guides/team/engineering_levels.md
Add link from guide to open role list
Fix italics treatment in CLA docs.
> content: add link to open roles

- src/content/learn/guides/vaults/aead_aes_128_gcm/README.md
- src/content/learn/guides/vaults/ecdh/README.md
- src/content/learn/guides/vaults/hkdf_sha256/README.md
- src/content/learn/guides/vaults/setup/README.md
- src/content/learn/guides/vaults/sha256/README.md
Adds guides for:
* Default setup
* Random bytes generate
* SHA256
* ECDH
* HKDF-SHA256
* AEAD AES GCM
> docs: add vault guides

- src/content/learn/blog/public-key-encryption-explained.md
This pull request creates a new blog "Public Key Encryption Explained"
> content: add public key encryption blog

- src/components/Menu/MenuItems.js
- src/components/pages/product/azure/ConfigurationsSection.js
- src/components/pages/product/azure/DescriptionSection.js
- src/components/pages/product/influx/ConfigurationsSection.js
- src/components/pages/product/microchip/ConfigurationsSection.js
- src/components/pages/product/microchip/DescriptionSection.js
- src/pages/product/azure.js
- src/pages/product/index.js
- src/pages/product/influx.js
- src/pages/product/kafka.js
- src/pages/product/microchip.js
- src/pages/product/router.js
also updated the Product Menu titles and SEO page descriptions
> feat: new azure, influx, microchip page copy

- src/content/learn/guides/team/join_us.md
> fix: s/heros/heroes/

- src/content/learn/guides/add-ons/influxdb/README.md
- src/content/learn/guides/enrollment/guide.md
update style on both Enrollment and InfluxDB Ockam Add-on guides
> style: update formatting and naming of sections

- src/content/learn/how-to-guides/using-add-ons/enterprise/influxdb/connect-and-use-ockam-hub.md
- context: improve guide on influxdb add on with ockam hub
> influxdb and ockam hub gude

- src/content/learn/blog/diffie-hellman_key_exchange.md
This pull request creates a new blog "Diffie-Hellman Key Exchange: How Does it Work?"
> content: add diffie-hellman key exchange blog

- src/content/learn/how-to-guides/contributing/cla.md
> chore: add redirect for old CLA article URL

- dependencies_repos.csv
> add rust example guide dep

- src/content/learn/how-to-guides/high-performance-team/values_and_virtues_on_the_Ockam_Team.md
Fix up of https://github.com/ockam-network/website/pull/380
> docs: fix typo in values and virtues guide

- src/content/learn/how-to-guides/rust-sdk-code-examples/credentials.md
> docs: update credentials example

- src/content/learn/blog/why_iot_needs_secure_messaging.md
1. Add video
2. Add transcript
> secure messaging blog

- src/content/learn/how-to-guides/rust/01-workers/README.md
- src/content/learn/how-to-guides/rust/02-transports/README.md
- src/content/learn/how-to-guides/rust/03-hub/README.md
- src/content/learn/how-to-guides/rust/04-forwarding/README.md
Updates Rust Getting Started Guide examples to new TCP API and other changes.
> fix(docs): refresh rust guide

- src/content/learn/how-to-guides/rust/02-transports/README.md
- src/content/learn/how-to-guides/rust/03-hub/README.md
- src/content/learn/how-to-guides/rust/04-forwarding/README.md
- src/content/learn/how-to-guides/rust/get-started/README.md
Updates Rust guide to latest Secure Channel API
> docs: update website rust guide for new channel api

- src/content/learn/how-to-guides/high-performance-team/engineering_levels.md
This looks, walks and quacks like a typo. 🤔
> docs: fix typo on engineering_levels.md

- src/consts/paths.ts
- src/content/blog/fight_complexity_in_software_design.mdx
- src/content/blog/high_performance_team.mdx
- src/content/blog/iot_device_security.mdx
- src/content/blog/ockam_website_is_open_source.mdx
- src/content/blog/open_source_as_an_integrator.mdx
- src/content/blog/public-key-encryption-explained.mdx
- src/content/blog/where_should_open_source_communities_chat.mdx
- src/content/blog/your_first_open_source_contribution.mdx
- src/content/blog/zero_ipo.mdx
- src/layouts/BlogLayout/BlogLayoutSidebar.jsx
- src/pages/blog/[slug].js
- src/pages/blog/index.js
- src/views/homepage/GetStarted.tsx
- src/views/homepage/Hero.tsx
- src/views/team/Hero.tsx
fix: update the blog url
fix: remove dot from hero
fix: update mailto
fix: small UI blog improvements
> fix: fixes before release

- src/views/homepage/Cases.tsx
- src/views/mission/Virtues.tsx
Minor typo fixes in the use cases section and the virtues section
> fix: typos

- package-lock.json
- src/layouts/MainLayout/MainLayoutFooter.tsx
Earlier I raised an issue(#560) where the component mentioned above was not centre-aligned and I made the fix. If there is anything I need to change do tell me.
Earlier: 
After the fix:
> fix: 'Developers love Ockam' component is not center alligned

- src/views/homepage/GetStarted.tsx
> Prepare 566

- src/content/blog/join_the_team.mdx
Updating the Interview portion to reflect what the current process looks like.
> content: update join the team blog

- package.json
- src/components/Transition/Transition.tsx
- src/hooks/useEffectOnce.ts
- src/views/homepage/Cases.tsx
- src/views/homepage/GetStarted.tsx
- src/views/homepage/Packages.tsx
- src/views/homepage/Tools.tsx
In this PR, I worked on the animation of home page.
For the animation, I created a generic `useTransition()` hook to handle the transition with duration, delay, child render, and items to be render.
> Home Page Animation

- src/views/homepage/Tools.tsx
Updating the code block within Tools, to match what is currently in the quick start:
* Uses orchestrator
* Includes  comments
> content: update tools code to match quick start

- src/content/blog/how_grow_popular_open_source_github.mdx
> Fix: Typos in  how_grow_popular_open_source_github blog

- src/content/blog/connect_private_influxdb.mdx
> content: fix influxdb demo

- src/content/blog/routing.mdx
> content: routing blog post updates
